Traceback (most recent call last):
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
t_anal = np.zeros(col_pts.shape)
t_anal[:, 1] = -ct_pressure
for i in range(len(t_anal)):
    if abs(col_pts[i][0])>=a:
        t_anal[i][1] = -pz_pressure

plt.plot(col_pts[:, 0], t.reshape(-1, 2)[:, 1], ".")
plt.plot(col_pts[:, 0], t_anal[:, 1])

plt.legend(["BigWham", "Analytical"])
# plt.xlim([-1 - 10 * 2 * c / nelts, -1 + 10 * 2 * c / nelts])
plt.title("Traction solution")
plt.xlabel("Position along crack")
plt.ylabel("Traction")

print("Calculated pressure between x = -", a , " and +", a , "is = ", t[101])
print("Calculated pressure between |x| = ", a , " and ", c , " is = ", t[1])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
Cell [0;32mIn[5], line 16[0m
[1;32m     13[0m plt[38;5;241m.[39mxlabel([38;5;124m"[39m[38;5;124mPosition along crack[39m[38;5;124m"[39m)
[1;32m     14[0m plt[38;5;241m.[39mylabel([38;5;124m"[39m[38;5;124mTraction[39m[38;5;124m"[39m)
[0;32m---> 16[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mCalculated pressure between x = -[39m[38;5;124m"[39m, a , [38;5;124m"[39m[38;5;124m and +[39m[38;5;124m"[39m, a , [38;5;124m"[39m[38;5;124mis = [39m[38;5;124m"[39m, [43mt[49m[43m[[49m[38;5;241;43m101[39;49m[43m][49m)
[1;32m     17[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mCalculated pressure between |x| = [39m[38;5;124m"[39m, a , [38;5;124m"[39m[38;5;124m and [39m[38;5;124m"[39m, c , [38;5;124m"[39m[38;5;124m is = [39m[38;5;124m"[39m, t[[38;5;241m1[39m])

[0;31mIndexError[0m: index 101 is out of bounds for axis 0 with size 12

